var GAME_LEVELS = [
  ["                                                                                                             ",
   "  v  v   vx                                          x                                                       ",
   "          x                                         x x              x                                       ",
   "   @      x                                        x   x             x                                       ",
   "          x                o                      x     x        xxxxxxxxx                                   ",
   "          x                                      xxxxxxxxx           x                                       ",
   "          x              o % o                  x         x          x                                       ",
   "          x           xxxxxxxxx                x           x                                                 ",
   "          x         xxv                                                                                      ",
   "          x       xxx                                                                                        ",
   "   o      x       v      v        v v                                                                        ",
   "   x      x    xx                        xxxvxxv  v  v o                                                     ",
   "                                                xx xx xxxxx         xxxxxx                                   ",
   "             x              xxx                                                                              ",
   "          o           xx             x                         o                                             ",
   
   "  x xx   xxxxxxxxx                                            xxxx                                           ",
   "                                                o  o   o                                                     ",
   "                              xxxx   xxxx    xx xx xx xxxx                                                   ",
   "                                                                                                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                             ",
   "                                                                                                             "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                        o                                                                                     ",
   "                        x                  v   v   v   v                                                      ",
   "                       xvx                                                                                    ",
   "                      x   x                                                                                   ",
   "                                                                                                              ",
   "                                                                     o o                                      ",
   "                                                                    xx xx                                     ",
   "                                                 o                 x!!x!!x                                    ",
   "                                     xxxxx xx   xxx xxxxxx        x!!!!!!!x                                   ",
   "                                    xvx                            x!!!!!x                                    ",
   "                               x                                    x!!!x                                     ",
   "                           xxxxvx                                    x!x                                      ",
   "                                x               xxxxxxxxx             v                                       ",
   "   @          xxx      x        x                                                                             ",
   "xxxxxxxxxxx            x      o  x   %                                                                        ",
   "                     xxxxxxxxxxxxxxxxxx                                                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                 x   x    xxx   x   x             x         x     x    x    x                                 ",
   "                  x x    x   x  x   x             x         x     x    xx   x                                 ",
   "                   x     x   x  x   x              x       x      x    x x  x                                 ",
   "                   x     x   x  x   x               x  x  x       x    x  x x                                 ",
   "                   x     x   x  x   x                x x x        x    x   xx                                 ",
   "                   x      xxx    xxx                  x x         x    x    x                                 ",
   "                                                                                                              ",
   "                                                                                                              ",
   "   @                                                                                                          ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
